application:
  kafka:
    topic: "demo-topic"

spring:
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "demo-producer"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intercore
    username: postgres
    password: "@ncHocl&ffkfp)h"
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        ddl-auto: update
        use-new-id-generator-mappings: false
  data:
    rest:
      base-path: /data-api
    datasource:
      generate-unique-name: false
      name: intercore
management:
  info:
    git:
      mode: full
  endpoints:
    health:
      show-details: always
    web:
      base-patch: /management
      include: health, info, beans, conditions
logging:
  level:
    org.springframework.security: trace